# Generated by Django 5.2.7 on 2025-10-27 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clock_in_time", models.DateTimeField(auto_now_add=True)),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="Available", max_length=20)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Attendance",
                "verbose_name_plural": "User Attendance",
                "ordering": ["-clock_in_time"],
            },
        ),
    ]
