# Generated by Django 5.2.7 on 2025-10-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_gpstrackinghistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofOfExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("QC_Photo", "Quality Control Photo"),
                            ("POD_Photo", "Proof of Delivery Photo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qc_pod_photo", models.FileField(upload_to="proof_uploads/")),
                ("gps_latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("gps_longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("is_location_verified", models.BooleanField(default=False)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="proofs_provided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="user_management.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proof of Execution",
                "verbose_name_plural": "Proof of Execution",
                "ordering": ["-executed_at"],
            },
        ),
    ]
