# Generated by Django 5.2.7 on 2025-10-28 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0006_proofofexecution"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesVisitPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("visit_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("Visited", "Visited"),
                            ("Missed", "Missed"),
                        ],
                        default="Planned",
                        max_length=20,
                    ),
                ),
                ("visit_notes", models.TextField(blank=True, null=True)),
                ("missed_remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sales_rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Visit Plan",
                "verbose_name_plural": "Sales Visit Plans",
                "ordering": ["visit_date"],
            },
        ),
    ]
